<?php

return [
    'db_name' => env('DB_DATABASE', 'nntmux'),
    'items_per_page' => env('ITEMS_PER_PAGE', 50),
    'items_per_cover_page' => env('ITEMS_PER_COVER_PAGE', 20),
    'max_pager_results' => env('MAX_PAGER_RESULTS', 125000),
    'echocli' => env('ECHOCLI', true),
    'rename_par2' => env('RENAME_PAR2', true),
    'rename_music_mediainfo' => env('RENAME_MUSIC_MEDIAINFO', true),
    'cache_expiry_short' => (int) env('CACHE_EXPIRY_SHORT', 5),
    'cache_expiry_medium' => (int) env('CACHE_EXPIRY_MEDIUM', 10),
    'cache_expiry_long' => (int) env('CACHE_EXPIRY_LONG', 15),
    'admin_username' => env('ADMIN_USER', 'admin'),
    'admin_password' => env('ADMIN_PASS', 'admin'),
    'admin_email' => env('ADMIN_EMAIL', 'admin@example.com'),
    'crc_token' => env('CRC_TOKEN', null),
    'multiprocessing_max_child_time' => env('NN_MULTIPROCESSING_MAX_CHILD_TIME', 1800),
    'concurrency_timeout' => env('NN_CONCURRENCY_TIMEOUT'),
    'stream_fork_output' => env('STREAM_FORK_OUTPUT', false),
    'distributed_lock_seconds' => (int) env('NNTMUX_DISTRIBUTED_LOCK_SECONDS', 900),
    'distributed_long_lock_seconds' => (int) env('NNTMUX_DISTRIBUTED_LONG_LOCK_SECONDS', 3600),
    'distributed_lock_store' => env('NNTMUX_DISTRIBUTED_LOCK_STORE', 'redis'),
    'native_worker_shadow_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_SHADOW_ENABLED', false),
    'native_worker_lane_commit_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_LANE_COMMIT_ENABLED', env('NNTMUX_NATIVE_WORKER_FIRST_LANE_COMMIT_ENABLED', false)),
    'native_worker_first_lane_commit_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_FIRST_LANE_COMMIT_ENABLED', false),
    'native_worker_lane_execution_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_LANE_EXECUTION_ENABLED', false),
    'native_worker_post_additional_deferred_execution_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_POST_ADDITIONAL_DEFERRED_EXECUTION_ENABLED', false),
    'native_worker_binary' => env('NNTMUX_NATIVE_WORKER_BINARY'),
    'native_worker_timeout_seconds' => (float) env('NNTMUX_NATIVE_WORKER_TIMEOUT_SECONDS', 5),
    'native_worker_lane_timeout_seconds' => (float) env('NNTMUX_NATIVE_WORKER_LANE_TIMEOUT_SECONDS', 3600),
    'native_worker_artisan_binary' => env('NNTMUX_NATIVE_WORKER_ARTISAN_BINARY'),
    'native_worker_artisan_script' => env('NNTMUX_NATIVE_WORKER_ARTISAN_SCRIPT'),
    'native_worker_lane_max_processes' => (int) env('NNTMUX_NATIVE_WORKER_LANE_MAX_PROCESSES', 0),
    'native_worker_binaries_max_messages' => (int) env('NNTMUX_NATIVE_WORKER_BINARIES_MAX_MESSAGES', 0),
    'native_worker_binaries_max_headers' => (int) env('NNTMUX_NATIVE_WORKER_BINARIES_MAX_HEADERS', 0),
    'native_worker_backfill_qty' => (int) env('NNTMUX_NATIVE_WORKER_BACKFILL_QTY', 0),
    'native_worker_backfill_max_messages' => (int) env('NNTMUX_NATIVE_WORKER_BACKFILL_MAX_MESSAGES', 0),
    'native_worker_backfill_threads' => (int) env('NNTMUX_NATIVE_WORKER_BACKFILL_THREADS', 0),
    'native_worker_backfill_groups' => (int) env('NNTMUX_NATIVE_WORKER_BACKFILL_GROUPS', 0),
    'native_worker_backfill_days' => (int) env('NNTMUX_NATIVE_WORKER_BACKFILL_DAYS', 0),
    'native_worker_backfill_safe_date' => env('NNTMUX_NATIVE_WORKER_BACKFILL_SAFE_DATE'),
    'native_worker_backfill_min_articles' => (int) env('NNTMUX_NATIVE_WORKER_BACKFILL_MIN_ARTICLES', 0),
    'native_worker_nntp_overview_sample' => (int) env('NNTMUX_NATIVE_WORKER_NNTP_OVERVIEW_SAMPLE', 0),
    'native_worker_log_stderr_bytes' => (int) env('NNTMUX_NATIVE_WORKER_LOG_STDERR_BYTES', 2048),
    'native_worker_hashed_fixnames_commit_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_HASHED_FIXNAMES_COMMIT_ENABLED', false),
    'native_worker_hashed_fixnames_rename_prepass_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_HASHED_FIXNAMES_RENAME_PREPASS_ENABLED', false),
    'native_worker_hashed_fixnames_fail_closed_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_HASHED_FIXNAMES_FAIL_CLOSED_ENABLED', false),
    'native_worker_commit_test_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_COMMIT_TEST_ENABLED', false),
    'native_worker_removecrap_production_commit_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_REMOVECRAP_PRODUCTION_COMMIT_ENABLED', false),
    'native_worker_rename_apply_test_enabled' => (bool) env('NNTMUX_NATIVE_WORKER_RENAME_APPLY_TEST_ENABLED', false),
    'native_worker_mysql_dsn' => env('NNTMUX_NATIVE_WORKER_MYSQL_DSN'),
    'native_worker_redis_addr' => env('NNTMUX_NATIVE_WORKER_REDIS_ADDR'),
    'native_worker_commit_timeout_seconds' => (float) env('NNTMUX_NATIVE_WORKER_COMMIT_TIMEOUT_SECONDS', 30),
    'native_worker_commit_report_bytes' => (int) env('NNTMUX_NATIVE_WORKER_COMMIT_REPORT_BYTES', 1048576),
    'native_worker_rename_prepass_timeout_seconds' => (float) env('NNTMUX_NATIVE_WORKER_RENAME_PREPASS_TIMEOUT_SECONDS', 30),
    'native_worker_rename_prepass_report_bytes' => (int) env('NNTMUX_NATIVE_WORKER_RENAME_PREPASS_REPORT_BYTES', 1048576),
    'native_worker_search_outbox_limit' => (int) env('NNTMUX_NATIVE_WORKER_SEARCH_OUTBOX_LIMIT', 100),
    'native_worker_search_outbox_max_attempts' => (int) env('NNTMUX_NATIVE_WORKER_SEARCH_OUTBOX_MAX_ATTEMPTS', 5),
    'allow_large_cbp_fk_restore' => (bool) env('NNTMUX_ALLOW_LARGE_CBP_FK_RESTORE', false),
    'purge_inactive_users' => env('PURGE_INACTIVE_USERS', false),
    'purge_inactive_users_days' => env('PURGE_INACTIVE_USERS_DAYS', 180),
    'mysql_search_fallback' => env('MYSQL_SEARCH_FALLBACK', false), // Disable MySQL LIKE fallback when Manticore/Elasticsearch return no results

    /*
    |--------------------------------------------------------------------------
    | Release dedupe (import-time)
    |--------------------------------------------------------------------------
    |
    | Size tolerance for matching an existing release when deduping imports
    | (collections / NZB). Default 0.05 = ±5% on total bytes (par2/RAR drift).
    |
    */
    'release_dedupe_size_tolerance' => (float) env('RELEASE_DEDUPE_SIZE_TOLERANCE', 0.05),
    'btcpay_webhook_secret' => env('BTCPAY_SECRET'),
    'tmp_unrar_path' => env('TEMP_UNRAR_PATH', storage_path('tmp/unrar/')),
    'tmp_unzip_path' => env('TEMP_UNZIP_PATH', storage_path('tmp/unzip/')),
    'nzb_import_folder' => env('NZB_IMPORT_FOLDER'),
    'nzb_upload_folder' => env('NZB_UPLOAD_FOLDER'),
    'redis_fast_degrade' => (bool) env('REDIS_FAST_DEGRADE', true),
    'redis_tcp_check_seconds' => (float) env('REDIS_TCP_CHECK_SECONDS', 0.2),
    'body_preamble_deobfuscate_groups' => env('NNTMUX_BODY_PREAMBLE_DEOBFUSCATE_GROUPS', ''),
    'body_preamble_deobfuscate_limit' => (int) env('NNTMUX_BODY_PREAMBLE_DEOBFUSCATE_LIMIT', 0),
    'body_preamble_line_limit' => (int) env('NNTMUX_BODY_PREAMBLE_LINE_LIMIT', 8),
    'body_preamble_deobfuscate_max_seconds' => (float) env('NNTMUX_BODY_PREAMBLE_DEOBFUSCATE_MAX_SECONDS', 0),
    'categorization' => [
        'log' => (bool) env('NNTMUX_CATEGORIZATION_LOG', false),
    ],
];
